import {useState} from 'react';
import {ArrowRight,Copy,Check,WechatLogo,Plus,Minus} from '@phosphor-icons/react';
import {businessFacts,community,faqs} from './siteContent';

export function CommunityStats(){return <section className="community-stats" aria-label="VELO 实际经营数据"><div className="stats-note"><p className="eyebrow">从太原开始</p><h2>已有骑友，与我们同行。</h2></div><div className="business-number"><strong>{businessFacts.usage}</strong><span>位骑友累计使用</span></div><div className="business-number"><strong>{businessFacts.receipts}</strong><span>累计实收人民币</span></div><p className="stats-date">截至 {businessFacts.asOf} · 团队提供</p></section>}

export function FAQ(){const [open,setOpen]=useState(null);return <section className="faq-section" id="faq" aria-labelledby="faq-title"><div className="faq-intro"><p className="eyebrow">出发之前</p><h2 id="faq-title">你可能想知道。</h2><p>关于使用、路线与社群。</p></div><div className="faq-list">{faqs.map((item,i)=><div className="faq-item" key={item.question}><h3><button aria-expanded={open===i} aria-controls={`faq-answer-${i}`} onClick={()=>setOpen(open===i?null:i)}>{item.question}{open===i?<Minus size={17}/>:<Plus size={17}/>}</button></h3><div id={`faq-answer-${i}`} hidden={open!==i}><p>{item.answer}</p></div></div>)}</div></section>}

export function CommunityDialog(){const [copied,setCopied]=useState(false),[copyError,setCopyError]=useState(false);async function copy(){try{await navigator.clipboard.writeText(community.wechatId);setCopied(true);setCopyError(false)}catch{setCopyError(true);setCopied(false)}}return <div className="community-dialog-content"><WechatLogo size={42} weight="regular"/><p className="eyebrow">联系 VELO</p><h2 id="dialog-title">从一句你好开始。</h2><p>添加微信，聊聊夜骑团练、周末活动，<br/>或品牌、赞助与投资合作。<br/>加入社群后，可付费使用 VELO。</p><div className="wechat-id"><span>微信号</span><strong>{community.wechatId}</strong><button onClick={copy} aria-label="复制微信号">{copied?<Check size={18}/>:<Copy size={18}/>}<span>{copied?'已复制':'复制'}</span></button></div><p className="copy-status" role="status">{copyError?'可以长按或选中上方微信号复制。':copied?'打开微信，搜索并添加这个微信号。':'打开微信，搜索微信号添加好友。'}</p><a className="community-dialog-help" href="#faq" onClick={()=>document.querySelector('.dialog-close')?.click()}>先了解常见问题<ArrowRight size={15}/></a></div>}

export function SiteFooter({onJoin,onAbout}){return <footer className="mature-footer"><div className="footer-top"><a className="wordmark" href="#" aria-label="返回 VELO 首页"><span aria-hidden="true"/>VELO</a><nav aria-label="页脚导航"><a href="#how-it-works">如何使用</a><a href="#community">骑友社群</a><a href="#faq">常见问题</a><button onClick={onJoin}>联系与加入</button><button onClick={onAbout}>关于公司</button><a href={community.privacyUrl} target="_blank" rel="noreferrer">隐私政策</a></nav></div><div className="footer-bottom"><span>{community.company} 运营</span><a href="https://beian.miit.gov.cn/" target="_blank" rel="noreferrer">{community.icp}</a></div></footer>}
