import {useEffect,useRef,useState} from 'react';
import {PencilSimple,ArrowUUpLeft,Trash,DownloadSimple,Mountains} from '@phosphor-icons/react';
import {MapCanvas} from './MapCanvas';
import demoSegments from './data/demo-segments.json';
import {downloadTrip} from './tripExport';
import {sketchDistance,sketchTrip} from './sketchGeometry';
import {fetchSketchElevation,snapToRoad} from './sketchServices';
import {ElevationProfile} from './ElevationProfile';
import './sketch.css';
const context=[demoSegments.find(s=>s.id==='14942511')],empty=[];
export function SketchDemo(){
 const [drawing,setDrawing]=useState(false),[history,setHistory]=useState([]),[ready,setReady]=useState(false),[message,setMessage]=useState(''),[mode,setMode]=useState('raw'),[busy,setBusy]=useState('');
 const pending=useRef(null),generation=useRef(0);
 useEffect(()=>()=>{pending.current?.abort()},[]);
 const current=history.at(-1),points=current?.[mode]||empty,elevation=current?.[`${mode}Elevation`];
 function cancel(){pending.current?.abort();generation.current++;setBusy('')}
 function updateCurrent(patch){setHistory(items=>items.map((item,i)=>i===items.length-1?{...item,...patch}:item))}
 function finish(stroke){if(stroke.length<2||sketchDistance(stroke)<10){setMessage('再画长一点，连起起点和终点。');return}cancel();setHistory(v=>[...v,{raw:stroke}]);setMode('raw');setDrawing(false);setMessage('画好了。可以贴路，也可以直接看海拔。')}
 async function calculate(useRoad){cancel();const seq=generation.current,controller=new AbortController();pending.current=controller;const timer=setTimeout(()=>controller.abort(),30000);let route=points,kind=mode,roadDone=false;try{if(useRoad){kind='road';if(current.road){route=current.road}else{setBusy('贴路中…');route=await snapToRoad(current.raw,controller.signal);if(generation.current!==seq)return;updateCurrent({road:route});}setMode('road');roadDone=true;}if(current?.[`${kind}Elevation`]){setMessage('已切换到贴路结果。');return}setBusy('计算海拔…');const result=await fetchSketchElevation(route,controller.signal);if(generation.current!==seq)return;updateCurrent({[`${kind}Elevation`]:result});setMessage('海拔已更新，可以导出 GPX。')}catch(error){if(generation.current===seq)setMessage(error.name==='AbortError'?'计算超时，可以保留路线再重试。':roadDone?'贴路完成。'+error.message:error.message)}finally{clearTimeout(timer);if(generation.current===seq)setBusy('')}}
 return <div className="sketch-demo"><div className="sketch-heading"><span>手绘 · 贴路 · 海拔</span><h3>想走的路，画出来。</h3><p>保留原线，或用腾讯地图贴路。<br/>在这里体验 OSM 贴路与 GLO-30 海拔。</p></div><div className="sketch-toolbar" aria-label="手绘工具"><button className={drawing?'active':''} disabled={!ready} aria-pressed={drawing} onClick={()=>{cancel();setDrawing(v=>!v);setMessage('')}}><PencilSimple size={17}/>{drawing?'取消手绘':points.length?'重画':'开始手绘'}</button><button disabled={!history.length||drawing} onClick={()=>{cancel();setHistory(v=>v.slice(0,-1));setMode('raw');setMessage('已撤销。')}}><ArrowUUpLeft size={17}/>撤销</button><button disabled={!history.length||drawing} onClick={()=>{cancel();setHistory([]);setMode('raw');setMessage('可以重新画线。')}}><Trash size={17}/>清空</button></div><div className="sketch-map"><MapCanvas segments={context} compact ariaLabel="手绘路线地图" drawMode={drawing} drawnCoordinates={points} onDraw={finish} onReadyChange={setReady}/>{drawing&&<div className="sketch-map-hint">按住画线，松开完成</div>}</div><div className="sketch-route-options"><div aria-label="路线方式"><button aria-pressed={mode==='raw'} disabled={!current||drawing} onClick={()=>{cancel();setMode('raw');setMessage('已保留手绘原线。')}}>保留原线</button><button aria-pressed={mode==='road'} disabled={!current||drawing||Boolean(busy)} onClick={()=>calculate(true)}>自动贴路</button></div><button disabled={!points.length||drawing||Boolean(busy)} onClick={()=>calculate(false)}><Mountains size={16}/>看海拔</button></div><div className="sketch-result"><div><strong>{points.length?(sketchDistance(points)/1000).toFixed(2):'—'}</strong><span>公里 · {mode==='road'?'贴路':'原线'}</span></div><div><strong>{elevation?Math.round(elevation.climb_m):'—'}</strong><span>米爬升</span></div><button disabled={points.length<2||drawing||Boolean(busy)} onClick={()=>{const trip=sketchTrip(points);trip.elevationsM=elevation?.elevations_m;downloadTrip(trip,'gpx');setMessage('GPX 已准备下载。')}}><DownloadSimple size={17}/>导出 GPX</button></div>{elevation&&<div className="sketch-profile"><ElevationProfile profile={elevation.profile}/><span>海拔 · GLO-30</span></div>}<p className="sketch-status" role="status">{busy||message||'先移动、缩放地图，再开始手绘。'}</p></div>
}
